# Generated by Django 5.2.7 on 2025-11-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Ingrese la Fecha y Hora de la Cita')),
                ('reason', models.CharField(help_text='Ingrese el Motivo de la Cita', max_length=200)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('NO ASISTIO', 'No Asistio')], default='PENDIENTE', help_text='Seleccione el Estado de la Cita', max_length=13)),
                ('doctor_id', models.ForeignKey(help_text='Seleccione el Doctor', on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('patient_id', models.ForeignKey(help_text='Seleccione el Paciente', on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-appointment_date'],
                'constraints': [models.UniqueConstraint(fields=('patient_id', 'appointment_date'), name='unique_patient_appointment_time'), models.UniqueConstraint(fields=('doctor_id', 'appointment_date'), name='unique_doctor_appointment_time')],
            },
        ),
    ]
