# Generated by Django 5.2.7 on 2025-11-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria')], default='EFECTIVO', help_text='Seleccione el Método de Pago', max_length=25)),
                ('payment_date', models.DateField(auto_now_add=True, help_text='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Ingrese el monto', max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', help_text='Seleccione el Estado del Pago', max_length=12)),
                ('appointment_id', models.ForeignKey(help_text='Seleccione la cita', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
