# Generated by Django 5.2.7 on 2025-11-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='metodo_pago',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='estado_pago',
            new_name='payment_status',
        ),
    ]
