# Generated by Django 5.2.7 on 2025-11-02 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del medicamento', max_length=100)),
                ('presentation', models.CharField(help_text='Ingrese la presentación', max_length=100)),
                ('dose', models.CharField(help_text='Ingrese la dosis', max_length=50)),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True, help_text='Fecha de prescripción')),
                ('appointment_id', models.ForeignKey(help_text='Seleccione la cita', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Ingrese la cantidad', validators=[django.core.validators.MinValueValidator(1)])),
                ('indications', models.TextField(help_text='Ingrese las indicaciones')),
                ('medicine_id', models.ForeignKey(help_text='Seleccione el medicamento', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('prescription_id', models.ForeignKey(help_text='Seleccione la receta', on_delete=django.db.models.deletion.CASCADE, to='medicine.prescription')),
            ],
            options={
                'verbose_name': 'detalle de receta',
                'verbose_name_plural': 'detalles de receta',
                'constraints': [models.UniqueConstraint(fields=('prescription_id', 'medicine_id'), name='unique_prescription_medicine')],
            },
        ),
    ]
