# Generated by Django 5.2.7 on 2025-11-02 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el Nombre del Paciente', max_length=100)),
                ('last_name', models.CharField(help_text='Ingrese el Apellido del Paciente', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Others')], default='M', help_text='Ingrese el Genero del Paciente', max_length=1)),
                ('type_document', models.CharField(choices=[('R.C', 'Registro Civil'), ('T.I', 'Tarjeta de Identidad'), ('C.C', 'Cedula de Ciudadania'), ('C.E', 'Cedula de Extranjeria'), ('PAS', 'Pasaporte')], default='R.C', help_text='Ingrese el Tipo de Documento del Paciente', max_length=3)),
                ('documentnumber', models.CharField(help_text='Ingrese el # de Documento del Paciente', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe tener solo dígitos (8 a 10 numeros(sin puntos, letras o comas)).', regex='^\\d{8,10}$')])),
                ('birth_date', models.DateField(help_text='Ingrese la Fecha de Nacimiento del Paciente')),
                ('address', models.CharField(help_text='Ingrese la Direccion del Paciente', max_length=100)),
                ('telephone', models.CharField(help_text='Ingrese el Telefono del Paciente', max_length=10)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialtyname', models.CharField(help_text='Ingrese el Nombre de la Especialidad', max_length=100)),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el Nombre del Doctor', max_length=100)),
                ('last_name', models.CharField(help_text='Ingrese el Apellido del Doctor', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Others')], default='M', help_text='Ingrese el Genero del Doctor', max_length=1)),
                ('telephone', models.CharField(help_text='Ingrese el Telefono del Doctor', max_length=10)),
                ('email', models.EmailField(help_text='Ingrese el Correo del Doctor', max_length=254)),
                ('specialty_id', models.ForeignKey(help_text='Seleccione la Especialidad del Doctor', on_delete=django.db.models.deletion.CASCADE, to='user.specialty')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
            },
        ),
    ]
