# Generated by Django 5.2.7 on 2025-11-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Acivo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Ingrese el Estado del Doctor', max_length=8),
        ),
    ]
