# Generated by Django 5.2.7 on 2025-11-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Ingrese el Estado del Paciente', max_length=8),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Ingrese el Estado del Doctor', max_length=8),
        ),
    ]
