# Generated by Django 5.2.7 on 2025-11-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Ingrese la Descripcion del Diagnostico Realizado')),
                ('appointment_id', models.ForeignKey(help_text='Seleccione la Cita Asociada al Diagnostico', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Ingrese la Descripcion del Procedimiemto Realizado')),
                ('appointment_id', models.ForeignKey(help_text='Seleccione la Cita Asociada al Diagnostico', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'Procedimiento Medico',
                'verbose_name_plural': 'Procedimientos Medicos',
            },
        ),
    ]
